apiVersion: v1
kind: Pod
metadata:
  name: demoworkloadidentity
  namespace: wip
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - name: msalwipdemo
      image: <ACRname>.azurecr.io/msalwipdemo:latest
      imagePullPolicy: Always
  imagePullSecrets:
    - name: acr-secret
